pinetab: Use qemu.sf.lcd_density instead of ro.sf.lcd_density
qemu.sf.lcd_density wil override the density at runtime.

Fixes the error:

    error: found duplicate sysprop assignments:
    ro.sf.lcd_density=160
    ro.sf.lcd_density=160
    ro.sf.lcd_density=151

Signed-off-by: Roman Stratiienko <r.stratiienko@gmail.com>